version: "3.8"

services:
  proxy:
    build:
      context: ./nginx
    ports:
      - "8080:8080"

  backend:
    image: dbofmmbt/mirror-server
    environment:
      - SERVER_PORT=8080

  any_domain:
    image: dbofmmbt/mirror-server
    environment:
      - SERVER_NAME=ANY_DOMAIN_MOCK
    networks:
      default:
        aliases:
          - "any_domain.com"

  tests:
    build:
      context: ./tests
    volumes:
      - ./tests:/tests
    depends_on:
      - proxy
